[package]
name = "abc335"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc335-a = { alias = "a", problem = "https://atcoder.jp/contests/abc335/tasks/abc335_a" }
abc335-b = { alias = "b", problem = "https://atcoder.jp/contests/abc335/tasks/abc335_b" }
abc335-c = { alias = "c", problem = "https://atcoder.jp/contests/abc335/tasks/abc335_c" }
abc335-d = { alias = "d", problem = "https://atcoder.jp/contests/abc335/tasks/abc335_d" }
abc335-e = { alias = "e", problem = "https://atcoder.jp/contests/abc335/tasks/abc335_e" }
abc335-f = { alias = "f", problem = "https://atcoder.jp/contests/abc335/tasks/abc335_f" }
abc335-g = { alias = "g", problem = "https://atcoder.jp/contests/abc335/tasks/abc335_g" }

[[bin]]
name = "abc335-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc335-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc335-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc335-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc335-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc335-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc335-g"
path = "src/bin/g.rs"

[dependencies]
proconio = { version = "=0.3.6", features = ["derive"] }

[dev-dependencies]
