[package]
name = "abc353"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc353-a = { alias = "a", problem = "https://atcoder.jp/contests/abc353/tasks/abc353_a" }
abc353-b = { alias = "b", problem = "https://atcoder.jp/contests/abc353/tasks/abc353_b" }
abc353-c = { alias = "c", problem = "https://atcoder.jp/contests/abc353/tasks/abc353_c" }
abc353-d = { alias = "d", problem = "https://atcoder.jp/contests/abc353/tasks/abc353_d" }
abc353-e = { alias = "e", problem = "https://atcoder.jp/contests/abc353/tasks/abc353_e" }
abc353-f = { alias = "f", problem = "https://atcoder.jp/contests/abc353/tasks/abc353_f" }
abc353-g = { alias = "g", problem = "https://atcoder.jp/contests/abc353/tasks/abc353_g" }

[[bin]]
name = "abc353-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc353-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc353-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc353-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc353-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc353-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc353-g"
path = "src/bin/g.rs"

[dependencies]
proconio = { version = "=0.4.5", features = ["derive"] }
ac-library-rs = "=0.1.1"
superslice = "1.0.0"

[dev-dependencies]
