[package]
name = "abc393"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc393-a = { alias = "a", problem = "https://atcoder.jp/contests/abc393/tasks/abc393_a" }
abc393-b = { alias = "b", problem = "https://atcoder.jp/contests/abc393/tasks/abc393_b" }
abc393-c = { alias = "c", problem = "https://atcoder.jp/contests/abc393/tasks/abc393_c" }
abc393-d = { alias = "d", problem = "https://atcoder.jp/contests/abc393/tasks/abc393_d" }
abc393-e = { alias = "e", problem = "https://atcoder.jp/contests/abc393/tasks/abc393_e" }
abc393-f = { alias = "f", problem = "https://atcoder.jp/contests/abc393/tasks/abc393_f" }
abc393-g = { alias = "g", problem = "https://atcoder.jp/contests/abc393/tasks/abc393_g" }

[[bin]]
name = "abc393-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc393-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc393-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc393-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc393-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc393-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc393-g"
path = "src/bin/g.rs"

[dependencies]
proconio = { version = "=0.4.5", features = ["derive"] }
ac-library-rs = "=0.1.1"
superslice = "1.0.0"
itertools = "=0.11.0"
rustc-hash = "=1.1.0"

[dev-dependencies]
