[package]
name = "abc391"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc391-a = { alias = "a", problem = "https://atcoder.jp/contests/abc391/tasks/abc391_a" }
abc391-b = { alias = "b", problem = "https://atcoder.jp/contests/abc391/tasks/abc391_b" }
abc391-c = { alias = "c", problem = "https://atcoder.jp/contests/abc391/tasks/abc391_c" }
abc391-d = { alias = "d", problem = "https://atcoder.jp/contests/abc391/tasks/abc391_d" }
abc391-e = { alias = "e", problem = "https://atcoder.jp/contests/abc391/tasks/abc391_e" }
abc391-f = { alias = "f", problem = "https://atcoder.jp/contests/abc391/tasks/abc391_f" }
abc391-g = { alias = "g", problem = "https://atcoder.jp/contests/abc391/tasks/abc391_g" }

[[bin]]
name = "abc391-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc391-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc391-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc391-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc391-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc391-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc391-g"
path = "src/bin/g.rs"

[dependencies]
proconio = { version = "=0.4.5", features = ["derive"] }
ac-library-rs = "=0.1.1"
superslice = "1.0.0"
itertools = "=0.11.0"
rustc-hash = "=1.1.0"

[dev-dependencies]
