[package]
name = "abc130"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc130-a = { alias = "a", problem = "https://atcoder.jp/contests/abc130/tasks/abc130_a" }
abc130-b = { alias = "b", problem = "https://atcoder.jp/contests/abc130/tasks/abc130_b" }
abc130-c = { alias = "c", problem = "https://atcoder.jp/contests/abc130/tasks/abc130_c" }
abc130-d = { alias = "d", problem = "https://atcoder.jp/contests/abc130/tasks/abc130_d" }
abc130-e = { alias = "e", problem = "https://atcoder.jp/contests/abc130/tasks/abc130_e" }
abc130-f = { alias = "f", problem = "https://atcoder.jp/contests/abc130/tasks/abc130_f" }

[[bin]]
name = "abc130-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc130-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc130-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc130-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc130-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc130-f"
path = "src/bin/f.rs"

[dependencies]
proconio = { version = "=0.3.6", features = ["derive"] }

[dev-dependencies]
