[package]
name = "abc348"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc348-a = { alias = "a", problem = "https://atcoder.jp/contests/abc348/tasks/abc348_a" }
abc348-b = { alias = "b", problem = "https://atcoder.jp/contests/abc348/tasks/abc348_b" }
abc348-c = { alias = "c", problem = "https://atcoder.jp/contests/abc348/tasks/abc348_c" }
abc348-d = { alias = "d", problem = "https://atcoder.jp/contests/abc348/tasks/abc348_d" }
abc348-e = { alias = "e", problem = "https://atcoder.jp/contests/abc348/tasks/abc348_e" }
abc348-f = { alias = "f", problem = "https://atcoder.jp/contests/abc348/tasks/abc348_f" }
abc348-g = { alias = "g", problem = "https://atcoder.jp/contests/abc348/tasks/abc348_g" }

[[bin]]
name = "abc348-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc348-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc348-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc348-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc348-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc348-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc348-g"
path = "src/bin/g.rs"

[dependencies]
proconio = { version = "=0.4.5", features = ["derive"] }
ac-library-rs = "=0.1.1"
superslice = "1.0.0"
itertools = "=0.11.0"
rustc-hash = "=1.1.0"

[dev-dependencies]
