[package]
name = "abc243"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc243-a = { alias = "a", problem = "https://atcoder.jp/contests/abc243/tasks/abc243_a" }
abc243-b = { alias = "b", problem = "https://atcoder.jp/contests/abc243/tasks/abc243_b" }
abc243-c = { alias = "c", problem = "https://atcoder.jp/contests/abc243/tasks/abc243_c" }
abc243-d = { alias = "d", problem = "https://atcoder.jp/contests/abc243/tasks/abc243_d" }
abc243-e = { alias = "e", problem = "https://atcoder.jp/contests/abc243/tasks/abc243_e" }
abc243-ex = { alias = "ex", problem = "https://atcoder.jp/contests/abc243/tasks/abc243_h" }
abc243-f = { alias = "f", problem = "https://atcoder.jp/contests/abc243/tasks/abc243_f" }
abc243-g = { alias = "g", problem = "https://atcoder.jp/contests/abc243/tasks/abc243_g" }

[[bin]]
name = "abc243-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc243-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc243-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc243-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc243-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc243-ex"
path = "src/bin/ex.rs"

[[bin]]
name = "abc243-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc243-g"
path = "src/bin/g.rs"

[dependencies]
proconio = { version = "=0.3.6", features = ["derive"] }

[dev-dependencies]
