[package]
name = "abc370"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc370-a = { alias = "a", problem = "https://atcoder.jp/contests/abc370/tasks/abc370_a" }
abc370-b = { alias = "b", problem = "https://atcoder.jp/contests/abc370/tasks/abc370_b" }
abc370-c = { alias = "c", problem = "https://atcoder.jp/contests/abc370/tasks/abc370_c" }
abc370-d = { alias = "d", problem = "https://atcoder.jp/contests/abc370/tasks/abc370_d" }
abc370-e = { alias = "e", problem = "https://atcoder.jp/contests/abc370/tasks/abc370_e" }
abc370-f = { alias = "f", problem = "https://atcoder.jp/contests/abc370/tasks/abc370_f" }
abc370-g = { alias = "g", problem = "https://atcoder.jp/contests/abc370/tasks/abc370_g" }

[[bin]]
name = "abc370-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc370-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc370-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc370-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc370-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc370-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc370-g"
path = "src/bin/g.rs"

[dependencies]
proconio = { version = "=0.4.5", features = ["derive"] }
ac-library-rs = "=0.1.1"
superslice = "1.0.0"
itertools = "0.13.0"

[dev-dependencies]
