[package]
name = "abc398"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc398-a = { alias = "a", problem = "https://atcoder.jp/contests/abc398/tasks/abc398_a" }
abc398-b = { alias = "b", problem = "https://atcoder.jp/contests/abc398/tasks/abc398_b" }
abc398-c = { alias = "c", problem = "https://atcoder.jp/contests/abc398/tasks/abc398_c" }
abc398-d = { alias = "d", problem = "https://atcoder.jp/contests/abc398/tasks/abc398_d" }
abc398-e = { alias = "e", problem = "https://atcoder.jp/contests/abc398/tasks/abc398_e" }
abc398-f = { alias = "f", problem = "https://atcoder.jp/contests/abc398/tasks/abc398_f" }
abc398-g = { alias = "g", problem = "https://atcoder.jp/contests/abc398/tasks/abc398_g" }

[[bin]]
name = "abc398-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc398-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc398-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc398-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc398-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc398-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc398-g"
path = "src/bin/g.rs"

[dependencies]
proconio = { version = "=0.4.5", features = ["derive"] }
ac-library-rs = "=0.1.1"
superslice = "1.0.0"
itertools = "=0.11.0"
rustc-hash = "=1.1.0"
rand = "0.8.5"

[dev-dependencies]
