[package]
name = "abc407"
version = "0.1.0"
edition = "2021"

[package.metadata.cargo-compete.bin]
abc407-a = { alias = "a", problem = "https://atcoder.jp/contests/abc407/tasks/abc407_a" }
abc407-b = { alias = "b", problem = "https://atcoder.jp/contests/abc407/tasks/abc407_b" }
abc407-c = { alias = "c", problem = "https://atcoder.jp/contests/abc407/tasks/abc407_c" }
abc407-d = { alias = "d", problem = "https://atcoder.jp/contests/abc407/tasks/abc407_d" }
abc407-e = { alias = "e", problem = "https://atcoder.jp/contests/abc407/tasks/abc407_e" }
abc407-f = { alias = "f", problem = "https://atcoder.jp/contests/abc407/tasks/abc407_f" }
abc407-g = { alias = "g", problem = "https://atcoder.jp/contests/abc407/tasks/abc407_g" }

[[bin]]
name = "abc407-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc407-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc407-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc407-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc407-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc407-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc407-g"
path = "src/bin/g.rs"

[dependencies]
proconio = { version = "=0.4.5", features = ["derive"] }
ac-library-rs = "=0.1.1"
superslice = "1.0.0"
itertools = "=0.11.0"
num = "=0.4.1"
num-bigint = "=0.4.3"
num-complex = "=0.4.3"
num-integer = "=0.1.45"
num-iter = "=0.1.43"
num-rational = "=0.4.1"
num-traits = "=0.2.15"
num-derive = "=0.4.0"
rustc-hash = "=1.1.0"
rand = "=0.8.5"

[dev-dependencies]
