[package]
name = "abc386"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc386-a = { alias = "a", problem = "https://atcoder.jp/contests/abc386/tasks/abc386_a" }
abc386-b = { alias = "b", problem = "https://atcoder.jp/contests/abc386/tasks/abc386_b" }
abc386-c = { alias = "c", problem = "https://atcoder.jp/contests/abc386/tasks/abc386_c" }
abc386-d = { alias = "d", problem = "https://atcoder.jp/contests/abc386/tasks/abc386_d" }
abc386-e = { alias = "e", problem = "https://atcoder.jp/contests/abc386/tasks/abc386_e" }
abc386-f = { alias = "f", problem = "https://atcoder.jp/contests/abc386/tasks/abc386_f" }
abc386-g = { alias = "g", problem = "https://atcoder.jp/contests/abc386/tasks/abc386_g" }

[[bin]]
name = "abc386-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc386-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc386-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc386-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc386-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc386-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc386-g"
path = "src/bin/g.rs"

[dependencies]
proconio = { version = "=0.4.5", features = ["derive"] }
ac-library-rs = "=0.1.1"
superslice = "1.0.0"
itertools = "=0.11.0"
rustc-hash = "=1.1.0"

[dev-dependencies]
