[package]
name = "abc323"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc323-a = { alias = "a", problem = "https://atcoder.jp/contests/abc323/tasks/abc323_a" }
abc323-b = { alias = "b", problem = "https://atcoder.jp/contests/abc323/tasks/abc323_b" }
abc323-c = { alias = "c", problem = "https://atcoder.jp/contests/abc323/tasks/abc323_c" }
abc323-d = { alias = "d", problem = "https://atcoder.jp/contests/abc323/tasks/abc323_d" }
abc323-e = { alias = "e", problem = "https://atcoder.jp/contests/abc323/tasks/abc323_e" }
abc323-f = { alias = "f", problem = "https://atcoder.jp/contests/abc323/tasks/abc323_f" }
abc323-g = { alias = "g", problem = "https://atcoder.jp/contests/abc323/tasks/abc323_g" }

[[bin]]
name = "abc323-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc323-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc323-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc323-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc323-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc323-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc323-g"
path = "src/bin/g.rs"

[dependencies]
proconio = { version = "=0.4.5", features = ["derive"] }
ac-library-rs = "=0.1.1"
superslice = "1.0.0"
itertools = "=0.11.0"
rustc-hash = "=1.1.0"

[dev-dependencies]
