[package]
name = "abc333"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc333-a = { alias = "a", problem = "https://atcoder.jp/contests/abc333/tasks/abc333_a" }
abc333-b = { alias = "b", problem = "https://atcoder.jp/contests/abc333/tasks/abc333_b" }
abc333-c = { alias = "c", problem = "https://atcoder.jp/contests/abc333/tasks/abc333_c" }
abc333-d = { alias = "d", problem = "https://atcoder.jp/contests/abc333/tasks/abc333_d" }
abc333-e = { alias = "e", problem = "https://atcoder.jp/contests/abc333/tasks/abc333_e" }
abc333-f = { alias = "f", problem = "https://atcoder.jp/contests/abc333/tasks/abc333_f" }
abc333-g = { alias = "g", problem = "https://atcoder.jp/contests/abc333/tasks/abc333_g" }

[[bin]]
name = "abc333-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc333-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc333-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc333-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc333-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc333-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc333-g"
path = "src/bin/g.rs"

[dependencies]
proconio = { version = "=0.3.6", features = ["derive"] }

[dev-dependencies]
