[package]
name = "arc044"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
arc044-a = { alias = "a", problem = "https://atcoder.jp/contests/arc044/tasks/arc044_a" }
arc044-b = { alias = "b", problem = "https://atcoder.jp/contests/arc044/tasks/arc044_b" }
arc044-c = { alias = "c", problem = "https://atcoder.jp/contests/arc044/tasks/arc044_c" }
arc044-d = { alias = "d", problem = "https://atcoder.jp/contests/arc044/tasks/arc044_d" }

[[bin]]
name = "arc044-a"
path = "src/bin/a.rs"

[[bin]]
name = "arc044-b"
path = "src/bin/b.rs"

[[bin]]
name = "arc044-c"
path = "src/bin/c.rs"

[[bin]]
name = "arc044-d"
path = "src/bin/d.rs"

[dependencies]
proconio = { version = "=0.3.6", features = ["derive"] }

[dev-dependencies]
