[package]
name = "abc215"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc215-a = { alias = "a", problem = "https://atcoder.jp/contests/abc215/tasks/abc215_a" }
abc215-b = { alias = "b", problem = "https://atcoder.jp/contests/abc215/tasks/abc215_b" }
abc215-c = { alias = "c", problem = "https://atcoder.jp/contests/abc215/tasks/abc215_c" }
abc215-d = { alias = "d", problem = "https://atcoder.jp/contests/abc215/tasks/abc215_d" }
abc215-e = { alias = "e", problem = "https://atcoder.jp/contests/abc215/tasks/abc215_e" }
abc215-f = { alias = "f", problem = "https://atcoder.jp/contests/abc215/tasks/abc215_f" }
abc215-g = { alias = "g", problem = "https://atcoder.jp/contests/abc215/tasks/abc215_g" }
abc215-h = { alias = "h", problem = "https://atcoder.jp/contests/abc215/tasks/abc215_h" }

[[bin]]
name = "abc215-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc215-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc215-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc215-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc215-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc215-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc215-g"
path = "src/bin/g.rs"

[[bin]]
name = "abc215-h"
path = "src/bin/h.rs"

[dependencies]
itertools = "0.12.0"
num-integer = "0.1.45"
proconio = { version = "=0.3.6", features = ["derive"] }

[dev-dependencies]
