[package]
name = "abc326"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc326-a = { alias = "a", problem = "https://atcoder.jp/contests/abc326/tasks/abc326_a" }
abc326-b = { alias = "b", problem = "https://atcoder.jp/contests/abc326/tasks/abc326_b" }
abc326-c = { alias = "c", problem = "https://atcoder.jp/contests/abc326/tasks/abc326_c" }
abc326-d = { alias = "d", problem = "https://atcoder.jp/contests/abc326/tasks/abc326_d" }
abc326-e = { alias = "e", problem = "https://atcoder.jp/contests/abc326/tasks/abc326_e" }
abc326-f = { alias = "f", problem = "https://atcoder.jp/contests/abc326/tasks/abc326_f" }
abc326-g = { alias = "g", problem = "https://atcoder.jp/contests/abc326/tasks/abc326_g" }

[[bin]]
name = "abc326-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc326-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc326-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc326-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc326-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc326-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc326-g"
path = "src/bin/g.rs"

[dependencies]
itertools = "0.12.0"
proconio = { version = "=0.3.6", features = ["derive"] }

[dev-dependencies]
