[package]
name = "abc225"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc225-a = { alias = "a", problem = "https://atcoder.jp/contests/abc225/tasks/abc225_a" }
abc225-b = { alias = "b", problem = "https://atcoder.jp/contests/abc225/tasks/abc225_b" }
abc225-c = { alias = "c", problem = "https://atcoder.jp/contests/abc225/tasks/abc225_c" }
abc225-d = { alias = "d", problem = "https://atcoder.jp/contests/abc225/tasks/abc225_d" }
abc225-e = { alias = "e", problem = "https://atcoder.jp/contests/abc225/tasks/abc225_e" }
abc225-f = { alias = "f", problem = "https://atcoder.jp/contests/abc225/tasks/abc225_f" }
abc225-g = { alias = "g", problem = "https://atcoder.jp/contests/abc225/tasks/abc225_g" }
abc225-h = { alias = "h", problem = "https://atcoder.jp/contests/abc225/tasks/abc225_h" }

[[bin]]
name = "abc225-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc225-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc225-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc225-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc225-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc225-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc225-g"
path = "src/bin/g.rs"

[[bin]]
name = "abc225-h"
path = "src/bin/h.rs"

[dependencies]
proconio = { version = "=0.3.6", features = ["derive"] }

[dev-dependencies]
