[package]
name = "abc212"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc212-a = { alias = "a", problem = "https://atcoder.jp/contests/abc212/tasks/abc212_a" }
abc212-b = { alias = "b", problem = "https://atcoder.jp/contests/abc212/tasks/abc212_b" }
abc212-c = { alias = "c", problem = "https://atcoder.jp/contests/abc212/tasks/abc212_c" }
abc212-d = { alias = "d", problem = "https://atcoder.jp/contests/abc212/tasks/abc212_d" }
abc212-e = { alias = "e", problem = "https://atcoder.jp/contests/abc212/tasks/abc212_e" }
abc212-f = { alias = "f", problem = "https://atcoder.jp/contests/abc212/tasks/abc212_f" }
abc212-g = { alias = "g", problem = "https://atcoder.jp/contests/abc212/tasks/abc212_g" }
abc212-h = { alias = "h", problem = "https://atcoder.jp/contests/abc212/tasks/abc212_h" }

[[bin]]
name = "abc212-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc212-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc212-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc212-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc212-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc212-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc212-g"
path = "src/bin/g.rs"

[[bin]]
name = "abc212-h"
path = "src/bin/h.rs"

[dependencies]
proconio = { version = "=0.3.6", features = ["derive"] }

[dev-dependencies]
