[package]
name = "abc340"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc340-a = { alias = "a", problem = "https://atcoder.jp/contests/abc340/tasks/abc340_a" }
abc340-b = { alias = "b", problem = "https://atcoder.jp/contests/abc340/tasks/abc340_b" }
abc340-c = { alias = "c", problem = "https://atcoder.jp/contests/abc340/tasks/abc340_c" }
abc340-d = { alias = "d", problem = "https://atcoder.jp/contests/abc340/tasks/abc340_d" }
abc340-e = { alias = "e", problem = "https://atcoder.jp/contests/abc340/tasks/abc340_e" }
abc340-f = { alias = "f", problem = "https://atcoder.jp/contests/abc340/tasks/abc340_f" }
abc340-g = { alias = "g", problem = "https://atcoder.jp/contests/abc340/tasks/abc340_g" }

[[bin]]
name = "abc340-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc340-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc340-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc340-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc340-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc340-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc340-g"
path = "src/bin/g.rs"

[dependencies]
proconio = { version = "=0.4.5", features = ["derive"] }
ac-library-rs = "=0.1.1"
superslice = "1.0.0"

[dev-dependencies]
