[package]
name = "abc240"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc240-a = { alias = "a", problem = "https://atcoder.jp/contests/abc240/tasks/abc240_a" }
abc240-b = { alias = "b", problem = "https://atcoder.jp/contests/abc240/tasks/abc240_b" }
abc240-c = { alias = "c", problem = "https://atcoder.jp/contests/abc240/tasks/abc240_c" }
abc240-d = { alias = "d", problem = "https://atcoder.jp/contests/abc240/tasks/abc240_d" }
abc240-e = { alias = "e", problem = "https://atcoder.jp/contests/abc240/tasks/abc240_e" }
abc240-ex = { alias = "ex", problem = "https://atcoder.jp/contests/abc240/tasks/abc240_h" }
abc240-f = { alias = "f", problem = "https://atcoder.jp/contests/abc240/tasks/abc240_f" }
abc240-g = { alias = "g", problem = "https://atcoder.jp/contests/abc240/tasks/abc240_g" }

[[bin]]
name = "abc240-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc240-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc240-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc240-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc240-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc240-ex"
path = "src/bin/ex.rs"

[[bin]]
name = "abc240-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc240-g"
path = "src/bin/g.rs"

[dependencies]
proconio = { version = "=0.3.6", features = ["derive"] }

[dev-dependencies]
