[package]
name = "abc325"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc325-a = { alias = "a", problem = "https://atcoder.jp/contests/abc325/tasks/abc325_a" }
abc325-b = { alias = "b", problem = "https://atcoder.jp/contests/abc325/tasks/abc325_b" }
abc325-c = { alias = "c", problem = "https://atcoder.jp/contests/abc325/tasks/abc325_c" }
abc325-d = { alias = "d", problem = "https://atcoder.jp/contests/abc325/tasks/abc325_d" }
abc325-e = { alias = "e", problem = "https://atcoder.jp/contests/abc325/tasks/abc325_e" }
abc325-f = { alias = "f", problem = "https://atcoder.jp/contests/abc325/tasks/abc325_f" }
abc325-g = { alias = "g", problem = "https://atcoder.jp/contests/abc325/tasks/abc325_g" }

[[bin]]
name = "abc325-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc325-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc325-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc325-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc325-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc325-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc325-g"
path = "src/bin/g.rs"

[dependencies]
proconio = { version = "=0.3.6", features = ["derive"] }

[dev-dependencies]
