[package]
name = "abc236"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc236-a = { alias = "a", problem = "https://atcoder.jp/contests/abc236/tasks/abc236_a" }
abc236-b = { alias = "b", problem = "https://atcoder.jp/contests/abc236/tasks/abc236_b" }
abc236-c = { alias = "c", problem = "https://atcoder.jp/contests/abc236/tasks/abc236_c" }
abc236-d = { alias = "d", problem = "https://atcoder.jp/contests/abc236/tasks/abc236_d" }
abc236-e = { alias = "e", problem = "https://atcoder.jp/contests/abc236/tasks/abc236_e" }
abc236-ex = { alias = "ex", problem = "https://atcoder.jp/contests/abc236/tasks/abc236_h" }
abc236-f = { alias = "f", problem = "https://atcoder.jp/contests/abc236/tasks/abc236_f" }
abc236-g = { alias = "g", problem = "https://atcoder.jp/contests/abc236/tasks/abc236_g" }

[[bin]]
name = "abc236-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc236-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc236-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc236-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc236-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc236-ex"
path = "src/bin/ex.rs"

[[bin]]
name = "abc236-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc236-g"
path = "src/bin/g.rs"

[dependencies]
proconio = { version = "=0.3.6", features = ["derive"] }

[dev-dependencies]
