[package]
name = "abc371"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc371-a = { alias = "a", problem = "https://atcoder.jp/contests/abc371/tasks/abc371_a" }
abc371-b = { alias = "b", problem = "https://atcoder.jp/contests/abc371/tasks/abc371_b" }
abc371-c = { alias = "c", problem = "https://atcoder.jp/contests/abc371/tasks/abc371_c" }
abc371-d = { alias = "d", problem = "https://atcoder.jp/contests/abc371/tasks/abc371_d" }
abc371-e = { alias = "e", problem = "https://atcoder.jp/contests/abc371/tasks/abc371_e" }
abc371-f = { alias = "f", problem = "https://atcoder.jp/contests/abc371/tasks/abc371_f" }
abc371-g = { alias = "g", problem = "https://atcoder.jp/contests/abc371/tasks/abc371_g" }

[[bin]]
name = "abc371-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc371-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc371-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc371-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc371-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc371-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc371-g"
path = "src/bin/g.rs"

[dependencies]
proconio = { version = "=0.4.5", features = ["derive"] }
ac-library-rs = "=0.1.1"
superslice = "1.0.0"
itertools = "0.13.0"

[dev-dependencies]
