[package]
name = "abc373"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc373-a = { alias = "a", problem = "https://atcoder.jp/contests/abc373/tasks/abc373_a" }
abc373-b = { alias = "b", problem = "https://atcoder.jp/contests/abc373/tasks/abc373_b" }
abc373-c = { alias = "c", problem = "https://atcoder.jp/contests/abc373/tasks/abc373_c" }
abc373-d = { alias = "d", problem = "https://atcoder.jp/contests/abc373/tasks/abc373_d" }
abc373-e = { alias = "e", problem = "https://atcoder.jp/contests/abc373/tasks/abc373_e" }
abc373-f = { alias = "f", problem = "https://atcoder.jp/contests/abc373/tasks/abc373_f" }
abc373-g = { alias = "g", problem = "https://atcoder.jp/contests/abc373/tasks/abc373_g" }

[[bin]]
name = "abc373-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc373-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc373-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc373-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc373-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc373-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc373-g"
path = "src/bin/g.rs"

[dependencies]
proconio = { version = "=0.4.5", features = ["derive"] }
ac-library-rs = "=0.1.1"
superslice = "1.0.0"
itertools = "0.13.0"

[dev-dependencies]
