[package]
name = "abc255"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc255-a = { alias = "a", problem = "https://atcoder.jp/contests/abc255/tasks/abc255_a" }
abc255-b = { alias = "b", problem = "https://atcoder.jp/contests/abc255/tasks/abc255_b" }
abc255-c = { alias = "c", problem = "https://atcoder.jp/contests/abc255/tasks/abc255_c" }
abc255-d = { alias = "d", problem = "https://atcoder.jp/contests/abc255/tasks/abc255_d" }
abc255-e = { alias = "e", problem = "https://atcoder.jp/contests/abc255/tasks/abc255_e" }
abc255-ex = { alias = "ex", problem = "https://atcoder.jp/contests/abc255/tasks/abc255_h" }
abc255-f = { alias = "f", problem = "https://atcoder.jp/contests/abc255/tasks/abc255_f" }
abc255-g = { alias = "g", problem = "https://atcoder.jp/contests/abc255/tasks/abc255_g" }

[[bin]]
name = "abc255-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc255-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc255-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc255-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc255-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc255-ex"
path = "src/bin/ex.rs"

[[bin]]
name = "abc255-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc255-g"
path = "src/bin/g.rs"

[dependencies]
proconio = { version = "=0.4.5", features = ["derive"] }
ac-library-rs = "=0.1.1"
superslice = "1.0.0"
itertools = "=0.11.0"
rustc-hash = "=1.1.0"
rand = "=0.8.5"

[dev-dependencies]
