[package]
name = "abc368"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc368-a = { alias = "a", problem = "https://atcoder.jp/contests/abc368/tasks/abc368_a" }
abc368-b = { alias = "b", problem = "https://atcoder.jp/contests/abc368/tasks/abc368_b" }
abc368-c = { alias = "c", problem = "https://atcoder.jp/contests/abc368/tasks/abc368_c" }
abc368-d = { alias = "d", problem = "https://atcoder.jp/contests/abc368/tasks/abc368_d" }
abc368-e = { alias = "e", problem = "https://atcoder.jp/contests/abc368/tasks/abc368_e" }
abc368-f = { alias = "f", problem = "https://atcoder.jp/contests/abc368/tasks/abc368_f" }
abc368-g = { alias = "g", problem = "https://atcoder.jp/contests/abc368/tasks/abc368_g" }

[[bin]]
name = "abc368-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc368-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc368-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc368-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc368-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc368-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc368-g"
path = "src/bin/g.rs"

[dependencies]
proconio = { version = "=0.4.5", features = ["derive"] }
ac-library-rs = "=0.1.1"
superslice = "1.0.0"

[dev-dependencies]
