[package]
name = "abc390"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc390-a = { alias = "a", problem = "https://atcoder.jp/contests/abc390/tasks/abc390_a" }
abc390-b = { alias = "b", problem = "https://atcoder.jp/contests/abc390/tasks/abc390_b" }
abc390-c = { alias = "c", problem = "https://atcoder.jp/contests/abc390/tasks/abc390_c" }
abc390-d = { alias = "d", problem = "https://atcoder.jp/contests/abc390/tasks/abc390_d" }
abc390-e = { alias = "e", problem = "https://atcoder.jp/contests/abc390/tasks/abc390_e" }
abc390-f = { alias = "f", problem = "https://atcoder.jp/contests/abc390/tasks/abc390_f" }
abc390-g = { alias = "g", problem = "https://atcoder.jp/contests/abc390/tasks/abc390_g" }

[[bin]]
name = "abc390-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc390-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc390-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc390-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc390-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc390-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc390-g"
path = "src/bin/g.rs"

[dependencies]
proconio = { version = "=0.4.5", features = ["derive"] }
ac-library-rs = "=0.1.1"
superslice = "1.0.0"
itertools = "=0.11.0"
rustc-hash = "=1.1.0"

[dev-dependencies]
