[package]
name = "abc379"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc379-a = { alias = "a", problem = "https://atcoder.jp/contests/abc379/tasks/abc379_a" }
abc379-b = { alias = "b", problem = "https://atcoder.jp/contests/abc379/tasks/abc379_b" }
abc379-c = { alias = "c", problem = "https://atcoder.jp/contests/abc379/tasks/abc379_c" }
abc379-d = { alias = "d", problem = "https://atcoder.jp/contests/abc379/tasks/abc379_d" }
abc379-e = { alias = "e", problem = "https://atcoder.jp/contests/abc379/tasks/abc379_e" }
abc379-f = { alias = "f", problem = "https://atcoder.jp/contests/abc379/tasks/abc379_f" }
abc379-g = { alias = "g", problem = "https://atcoder.jp/contests/abc379/tasks/abc379_g" }

[[bin]]
name = "abc379-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc379-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc379-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc379-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc379-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc379-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc379-g"
path = "src/bin/g.rs"

[dependencies]
proconio = { version = "=0.4.5", features = ["derive"] }
ac-library-rs = "=0.1.1"
superslice = "1.0.0"
itertools = "0.13.0"
num-bigint = "0.2.6"

[dev-dependencies]
