[package]
name = "abc248"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc248-a = { alias = "a", problem = "https://atcoder.jp/contests/abc248/tasks/abc248_a" }
abc248-b = { alias = "b", problem = "https://atcoder.jp/contests/abc248/tasks/abc248_b" }
abc248-c = { alias = "c", problem = "https://atcoder.jp/contests/abc248/tasks/abc248_c" }
abc248-d = { alias = "d", problem = "https://atcoder.jp/contests/abc248/tasks/abc248_d" }
abc248-e = { alias = "e", problem = "https://atcoder.jp/contests/abc248/tasks/abc248_e" }
abc248-ex = { alias = "ex", problem = "https://atcoder.jp/contests/abc248/tasks/abc248_h" }
abc248-f = { alias = "f", problem = "https://atcoder.jp/contests/abc248/tasks/abc248_f" }
abc248-g = { alias = "g", problem = "https://atcoder.jp/contests/abc248/tasks/abc248_g" }

[[bin]]
name = "abc248-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc248-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc248-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc248-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc248-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc248-ex"
path = "src/bin/ex.rs"

[[bin]]
name = "abc248-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc248-g"
path = "src/bin/g.rs"

[dependencies]
proconio = { version = "=0.3.6", features = ["derive"] }

[dev-dependencies]
