[package]
name = "abc397"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc397-a = { alias = "a", problem = "https://atcoder.jp/contests/abc397/tasks/abc397_a" }
abc397-b = { alias = "b", problem = "https://atcoder.jp/contests/abc397/tasks/abc397_b" }
abc397-c = { alias = "c", problem = "https://atcoder.jp/contests/abc397/tasks/abc397_c" }
abc397-d = { alias = "d", problem = "https://atcoder.jp/contests/abc397/tasks/abc397_d" }
abc397-e = { alias = "e", problem = "https://atcoder.jp/contests/abc397/tasks/abc397_e" }
abc397-f = { alias = "f", problem = "https://atcoder.jp/contests/abc397/tasks/abc397_f" }
abc397-g = { alias = "g", problem = "https://atcoder.jp/contests/abc397/tasks/abc397_g" }

[[bin]]
name = "abc397-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc397-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc397-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc397-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc397-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc397-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc397-g"
path = "src/bin/g.rs"

[dependencies]
proconio = { version = "=0.4.5", features = ["derive"] }
ac-library-rs = "=0.1.1"
superslice = "1.0.0"
itertools = "=0.11.0"
rustc-hash = "=1.1.0"

[dev-dependencies]
