[package]
name = "abc129"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc129-a = { alias = "a", problem = "https://atcoder.jp/contests/abc129/tasks/abc129_a" }
abc129-b = { alias = "b", problem = "https://atcoder.jp/contests/abc129/tasks/abc129_b" }
abc129-c = { alias = "c", problem = "https://atcoder.jp/contests/abc129/tasks/abc129_c" }
abc129-d = { alias = "d", problem = "https://atcoder.jp/contests/abc129/tasks/abc129_d" }
abc129-e = { alias = "e", problem = "https://atcoder.jp/contests/abc129/tasks/abc129_e" }
abc129-f = { alias = "f", problem = "https://atcoder.jp/contests/abc129/tasks/abc129_f" }

[[bin]]
name = "abc129-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc129-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc129-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc129-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc129-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc129-f"
path = "src/bin/f.rs"

[dependencies]
proconio = { version = "=0.3.6", features = ["derive"] }

[dev-dependencies]
