[package]
name = "abc352"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc352-a = { alias = "a", problem = "https://atcoder.jp/contests/abc352/tasks/abc352_a" }
abc352-b = { alias = "b", problem = "https://atcoder.jp/contests/abc352/tasks/abc352_b" }
abc352-c = { alias = "c", problem = "https://atcoder.jp/contests/abc352/tasks/abc352_c" }
abc352-d = { alias = "d", problem = "https://atcoder.jp/contests/abc352/tasks/abc352_d" }
abc352-e = { alias = "e", problem = "https://atcoder.jp/contests/abc352/tasks/abc352_e" }
abc352-f = { alias = "f", problem = "https://atcoder.jp/contests/abc352/tasks/abc352_f" }
abc352-g = { alias = "g", problem = "https://atcoder.jp/contests/abc352/tasks/abc352_g" }

[[bin]]
name = "abc352-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc352-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc352-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc352-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc352-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc352-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc352-g"
path = "src/bin/g.rs"

[dependencies]
proconio = { version = "=0.4.5", features = ["derive"] }
ac-library-rs = "=0.1.1"
superslice = "1.0.0"

[dev-dependencies]
