[package]
name = "abc331"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc331-a = { alias = "a", problem = "https://atcoder.jp/contests/abc331/tasks/abc331_a" }
abc331-b = { alias = "b", problem = "https://atcoder.jp/contests/abc331/tasks/abc331_b" }
abc331-c = { alias = "c", problem = "https://atcoder.jp/contests/abc331/tasks/abc331_c" }
abc331-d = { alias = "d", problem = "https://atcoder.jp/contests/abc331/tasks/abc331_d" }
abc331-e = { alias = "e", problem = "https://atcoder.jp/contests/abc331/tasks/abc331_e" }
abc331-f = { alias = "f", problem = "https://atcoder.jp/contests/abc331/tasks/abc331_f" }
abc331-g = { alias = "g", problem = "https://atcoder.jp/contests/abc331/tasks/abc331_g" }

[[bin]]
name = "abc331-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc331-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc331-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc331-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc331-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc331-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc331-g"
path = "src/bin/g.rs"

[dependencies]
proconio = { version = "=0.3.6", features = ["derive"] }
superslice = "1.0.0"

[dev-dependencies]
