[package]
name = "abc374"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc374-a = { alias = "a", problem = "https://atcoder.jp/contests/abc374/tasks/abc374_a" }
abc374-b = { alias = "b", problem = "https://atcoder.jp/contests/abc374/tasks/abc374_b" }
abc374-c = { alias = "c", problem = "https://atcoder.jp/contests/abc374/tasks/abc374_c" }
abc374-d = { alias = "d", problem = "https://atcoder.jp/contests/abc374/tasks/abc374_d" }
abc374-e = { alias = "e", problem = "https://atcoder.jp/contests/abc374/tasks/abc374_e" }
abc374-f = { alias = "f", problem = "https://atcoder.jp/contests/abc374/tasks/abc374_f" }
abc374-g = { alias = "g", problem = "https://atcoder.jp/contests/abc374/tasks/abc374_g" }

[[bin]]
name = "abc374-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc374-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc374-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc374-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc374-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc374-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc374-g"
path = "src/bin/g.rs"

[dependencies]
proconio = { version = "=0.4.5", features = ["derive"] }
ac-library-rs = "=0.1.1"
superslice = "1.0.0"
itertools = "0.13.0"

[dev-dependencies]
