[package]
name = "abc332"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc332-a = { alias = "a", problem = "https://atcoder.jp/contests/abc332/tasks/abc332_a" }
abc332-b = { alias = "b", problem = "https://atcoder.jp/contests/abc332/tasks/abc332_b" }
abc332-c = { alias = "c", problem = "https://atcoder.jp/contests/abc332/tasks/abc332_c" }
abc332-d = { alias = "d", problem = "https://atcoder.jp/contests/abc332/tasks/abc332_d" }
abc332-e = { alias = "e", problem = "https://atcoder.jp/contests/abc332/tasks/abc332_e" }
abc332-f = { alias = "f", problem = "https://atcoder.jp/contests/abc332/tasks/abc332_f" }
abc332-g = { alias = "g", problem = "https://atcoder.jp/contests/abc332/tasks/abc332_g" }

[[bin]]
name = "abc332-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc332-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc332-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc332-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc332-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc332-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc332-g"
path = "src/bin/g.rs"

[dependencies]
itertools = "0.12.0"
proconio = { version = "=0.3.6", features = ["derive"] }

[dev-dependencies]
