[package]
name = "abc363"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc363-a = { alias = "a", problem = "https://atcoder.jp/contests/abc363/tasks/abc363_a" }
abc363-b = { alias = "b", problem = "https://atcoder.jp/contests/abc363/tasks/abc363_b" }
abc363-c = { alias = "c", problem = "https://atcoder.jp/contests/abc363/tasks/abc363_c" }
abc363-d = { alias = "d", problem = "https://atcoder.jp/contests/abc363/tasks/abc363_d" }
abc363-e = { alias = "e", problem = "https://atcoder.jp/contests/abc363/tasks/abc363_e" }
abc363-f = { alias = "f", problem = "https://atcoder.jp/contests/abc363/tasks/abc363_f" }
abc363-g = { alias = "g", problem = "https://atcoder.jp/contests/abc363/tasks/abc363_g" }

[[bin]]
name = "abc363-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc363-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc363-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc363-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc363-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc363-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc363-g"
path = "src/bin/g.rs"

[dependencies]
proconio = { version = "=0.4.5", features = ["derive"] }
ac-library-rs = "=0.1.1"
superslice = "1.0.0"
itertools = "0.13.0"

[dev-dependencies]
