[package]
name = "abc291"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc291-a = { alias = "a", problem = "https://atcoder.jp/contests/abc291/tasks/abc291_a" }
abc291-b = { alias = "b", problem = "https://atcoder.jp/contests/abc291/tasks/abc291_b" }
abc291-c = { alias = "c", problem = "https://atcoder.jp/contests/abc291/tasks/abc291_c" }
abc291-d = { alias = "d", problem = "https://atcoder.jp/contests/abc291/tasks/abc291_d" }
abc291-e = { alias = "e", problem = "https://atcoder.jp/contests/abc291/tasks/abc291_e" }
abc291-ex = { alias = "ex", problem = "https://atcoder.jp/contests/abc291/tasks/abc291_h" }
abc291-f = { alias = "f", problem = "https://atcoder.jp/contests/abc291/tasks/abc291_f" }
abc291-g = { alias = "g", problem = "https://atcoder.jp/contests/abc291/tasks/abc291_g" }

[[bin]]
name = "abc291-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc291-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc291-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc291-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc291-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc291-ex"
path = "src/bin/ex.rs"

[[bin]]
name = "abc291-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc291-g"
path = "src/bin/g.rs"

[dependencies]
proconio = { version = "=0.3.6", features = ["derive"] }

[dev-dependencies]
