[package]
name = "abc322"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc322-a = { alias = "a", problem = "https://atcoder.jp/contests/abc322/tasks/abc322_a" }
abc322-b = { alias = "b", problem = "https://atcoder.jp/contests/abc322/tasks/abc322_b" }
abc322-c = { alias = "c", problem = "https://atcoder.jp/contests/abc322/tasks/abc322_c" }
abc322-d = { alias = "d", problem = "https://atcoder.jp/contests/abc322/tasks/abc322_d" }
abc322-e = { alias = "e", problem = "https://atcoder.jp/contests/abc322/tasks/abc322_e" }
abc322-f = { alias = "f", problem = "https://atcoder.jp/contests/abc322/tasks/abc322_f" }
abc322-g = { alias = "g", problem = "https://atcoder.jp/contests/abc322/tasks/abc322_g" }

[[bin]]
name = "abc322-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc322-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc322-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc322-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc322-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc322-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc322-g"
path = "src/bin/g.rs"

[dependencies]
itertools = "0.12.0"
proconio = { version = "=0.3.6", features = ["derive"] }

[dev-dependencies]
