[package]
name = "abc385"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc385-a = { alias = "a", problem = "https://atcoder.jp/contests/abc385/tasks/abc385_a" }
abc385-b = { alias = "b", problem = "https://atcoder.jp/contests/abc385/tasks/abc385_b" }
abc385-c = { alias = "c", problem = "https://atcoder.jp/contests/abc385/tasks/abc385_c" }
abc385-d = { alias = "d", problem = "https://atcoder.jp/contests/abc385/tasks/abc385_d" }
abc385-e = { alias = "e", problem = "https://atcoder.jp/contests/abc385/tasks/abc385_e" }
abc385-f = { alias = "f", problem = "https://atcoder.jp/contests/abc385/tasks/abc385_f" }
abc385-g = { alias = "g", problem = "https://atcoder.jp/contests/abc385/tasks/abc385_g" }

[[bin]]
name = "abc385-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc385-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc385-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc385-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc385-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc385-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc385-g"
path = "src/bin/g.rs"

[dependencies]
proconio = { version = "=0.4.5", features = ["derive"] }
ac-library-rs = "=0.1.1"
superslice = "1.0.0"
itertools = "0.13.0"

[dev-dependencies]
