[package]
name = "abc372"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc372-a = { alias = "a", problem = "https://atcoder.jp/contests/abc372/tasks/abc372_a" }
abc372-b = { alias = "b", problem = "https://atcoder.jp/contests/abc372/tasks/abc372_b" }
abc372-c = { alias = "c", problem = "https://atcoder.jp/contests/abc372/tasks/abc372_c" }
abc372-d = { alias = "d", problem = "https://atcoder.jp/contests/abc372/tasks/abc372_d" }
abc372-e = { alias = "e", problem = "https://atcoder.jp/contests/abc372/tasks/abc372_e" }
abc372-f = { alias = "f", problem = "https://atcoder.jp/contests/abc372/tasks/abc372_f" }
abc372-g = { alias = "g", problem = "https://atcoder.jp/contests/abc372/tasks/abc372_g" }

[[bin]]
name = "abc372-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc372-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc372-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc372-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc372-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc372-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc372-g"
path = "src/bin/g.rs"

[dependencies]
proconio = { version = "=0.4.5", features = ["derive"] }
ac-library-rs = "=0.1.1"
superslice = "1.0.0"
itertools = "0.13.0"

[dev-dependencies]
