[package]
name = "ahc039"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
ahc039-a = { alias = "a", problem = "https://atcoder.jp/contests/ahc039/tasks/ahc039_a" }

[[bin]]
name = "ahc039-a"
path = "src/bin/a.rs"

[dependencies]
proconio = { version = "=0.4.5", features = ["derive"] }
ac-library-rs = "=0.1.1"
superslice = "1.0.0"
itertools = "0.13.0"
rand = "0.8.5"

[dev-dependencies]
