[package]
name = "abc330"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc330-a = { alias = "a", problem = "https://atcoder.jp/contests/abc330/tasks/abc330_a" }
abc330-b = { alias = "b", problem = "https://atcoder.jp/contests/abc330/tasks/abc330_b" }
abc330-c = { alias = "c", problem = "https://atcoder.jp/contests/abc330/tasks/abc330_c" }
abc330-d = { alias = "d", problem = "https://atcoder.jp/contests/abc330/tasks/abc330_d" }
abc330-e = { alias = "e", problem = "https://atcoder.jp/contests/abc330/tasks/abc330_e" }
abc330-f = { alias = "f", problem = "https://atcoder.jp/contests/abc330/tasks/abc330_f" }
abc330-g = { alias = "g", problem = "https://atcoder.jp/contests/abc330/tasks/abc330_g" }

[[bin]]
name = "abc330-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc330-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc330-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc330-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc330-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc330-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc330-g"
path = "src/bin/g.rs"

[dependencies]
proconio = { version = "=0.3.6", features = ["derive"] }

[dev-dependencies]
