[package]
name = "abc355"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc355-a = { alias = "a", problem = "https://atcoder.jp/contests/abc355/tasks/abc355_a" }
abc355-b = { alias = "b", problem = "https://atcoder.jp/contests/abc355/tasks/abc355_b" }
abc355-c = { alias = "c", problem = "https://atcoder.jp/contests/abc355/tasks/abc355_c" }
abc355-d = { alias = "d", problem = "https://atcoder.jp/contests/abc355/tasks/abc355_d" }
abc355-e = { alias = "e", problem = "https://atcoder.jp/contests/abc355/tasks/abc355_e" }
abc355-f = { alias = "f", problem = "https://atcoder.jp/contests/abc355/tasks/abc355_f" }
abc355-g = { alias = "g", problem = "https://atcoder.jp/contests/abc355/tasks/abc355_g" }

[[bin]]
name = "abc355-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc355-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc355-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc355-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc355-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc355-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc355-g"
path = "src/bin/g.rs"

[dependencies]
proconio = { version = "=0.4.5", features = ["derive"] }
ac-library-rs = "=0.1.1"
superslice = "1.0.0"

[dev-dependencies]
