[package]
name = "abc389"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc389-a = { alias = "a", problem = "https://atcoder.jp/contests/abc389/tasks/abc389_a" }
abc389-b = { alias = "b", problem = "https://atcoder.jp/contests/abc389/tasks/abc389_b" }
abc389-c = { alias = "c", problem = "https://atcoder.jp/contests/abc389/tasks/abc389_c" }
abc389-d = { alias = "d", problem = "https://atcoder.jp/contests/abc389/tasks/abc389_d" }
abc389-e = { alias = "e", problem = "https://atcoder.jp/contests/abc389/tasks/abc389_e" }
abc389-f = { alias = "f", problem = "https://atcoder.jp/contests/abc389/tasks/abc389_f" }
abc389-g = { alias = "g", problem = "https://atcoder.jp/contests/abc389/tasks/abc389_g" }

[[bin]]
name = "abc389-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc389-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc389-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc389-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc389-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc389-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc389-g"
path = "src/bin/g.rs"

[dependencies]
proconio = { version = "=0.4.5", features = ["derive"] }
ac-library-rs = "=0.1.1"
superslice = "1.0.0"
itertools = "=0.11.0"
rustc-hash = "=1.1.0"

[dev-dependencies]
