[package]
name = "abc227"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc227-a = { alias = "a", problem = "https://atcoder.jp/contests/abc227/tasks/abc227_a" }
abc227-b = { alias = "b", problem = "https://atcoder.jp/contests/abc227/tasks/abc227_b" }
abc227-c = { alias = "c", problem = "https://atcoder.jp/contests/abc227/tasks/abc227_c" }
abc227-d = { alias = "d", problem = "https://atcoder.jp/contests/abc227/tasks/abc227_d" }
abc227-e = { alias = "e", problem = "https://atcoder.jp/contests/abc227/tasks/abc227_e" }
abc227-f = { alias = "f", problem = "https://atcoder.jp/contests/abc227/tasks/abc227_f" }
abc227-g = { alias = "g", problem = "https://atcoder.jp/contests/abc227/tasks/abc227_g" }
abc227-h = { alias = "h", problem = "https://atcoder.jp/contests/abc227/tasks/abc227_h" }

[[bin]]
name = "abc227-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc227-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc227-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc227-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc227-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc227-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc227-g"
path = "src/bin/g.rs"

[[bin]]
name = "abc227-h"
path = "src/bin/h.rs"

[dependencies]
proconio = { version = "=0.3.6", features = ["derive"] }

[dev-dependencies]
