[package]
name = "abc218"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc218-a = { alias = "a", problem = "https://atcoder.jp/contests/abc218/tasks/abc218_a" }
abc218-b = { alias = "b", problem = "https://atcoder.jp/contests/abc218/tasks/abc218_b" }
abc218-c = { alias = "c", problem = "https://atcoder.jp/contests/abc218/tasks/abc218_c" }
abc218-d = { alias = "d", problem = "https://atcoder.jp/contests/abc218/tasks/abc218_d" }
abc218-e = { alias = "e", problem = "https://atcoder.jp/contests/abc218/tasks/abc218_e" }
abc218-f = { alias = "f", problem = "https://atcoder.jp/contests/abc218/tasks/abc218_f" }
abc218-g = { alias = "g", problem = "https://atcoder.jp/contests/abc218/tasks/abc218_g" }
abc218-h = { alias = "h", problem = "https://atcoder.jp/contests/abc218/tasks/abc218_h" }

[[bin]]
name = "abc218-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc218-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc218-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc218-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc218-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc218-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc218-g"
path = "src/bin/g.rs"

[[bin]]
name = "abc218-h"
path = "src/bin/h.rs"

[dependencies]
proconio = { version = "=0.3.6", features = ["derive"] }

[dev-dependencies]
