[package]
name = "abc388"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc388-a = { alias = "a", problem = "https://atcoder.jp/contests/abc388/tasks/abc388_a" }
abc388-b = { alias = "b", problem = "https://atcoder.jp/contests/abc388/tasks/abc388_b" }
abc388-c = { alias = "c", problem = "https://atcoder.jp/contests/abc388/tasks/abc388_c" }
abc388-d = { alias = "d", problem = "https://atcoder.jp/contests/abc388/tasks/abc388_d" }
abc388-e = { alias = "e", problem = "https://atcoder.jp/contests/abc388/tasks/abc388_e" }
abc388-f = { alias = "f", problem = "https://atcoder.jp/contests/abc388/tasks/abc388_f" }
abc388-g = { alias = "g", problem = "https://atcoder.jp/contests/abc388/tasks/abc388_g" }

[[bin]]
name = "abc388-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc388-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc388-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc388-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc388-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc388-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc388-g"
path = "src/bin/g.rs"

[dependencies]
proconio = { version = "=0.4.5", features = ["derive"] }
ac-library-rs = "=0.1.1"
superslice = "1.0.0"
itertools = "=0.11.0"
rustc-hash = "=1.1.0"

[dev-dependencies]
