[package]
name = "abc346"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc346-a = { alias = "a", problem = "https://atcoder.jp/contests/abc346/tasks/abc346_a" }
abc346-b = { alias = "b", problem = "https://atcoder.jp/contests/abc346/tasks/abc346_b" }
abc346-c = { alias = "c", problem = "https://atcoder.jp/contests/abc346/tasks/abc346_c" }
abc346-d = { alias = "d", problem = "https://atcoder.jp/contests/abc346/tasks/abc346_d" }
abc346-e = { alias = "e", problem = "https://atcoder.jp/contests/abc346/tasks/abc346_e" }
abc346-f = { alias = "f", problem = "https://atcoder.jp/contests/abc346/tasks/abc346_f" }
abc346-g = { alias = "g", problem = "https://atcoder.jp/contests/abc346/tasks/abc346_g" }

[[bin]]
name = "abc346-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc346-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc346-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc346-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc346-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc346-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc346-g"
path = "src/bin/g.rs"

[dependencies]
proconio = { version = "=0.3.6", features = ["derive"] }

[dev-dependencies]
