[package]
name = "abc065"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc065-a = { alias = "a", problem = "https://atcoder.jp/contests/abc065/tasks/abc065_a" }
abc065-b = { alias = "b", problem = "https://atcoder.jp/contests/abc065/tasks/abc065_b" }
abc065-c = { alias = "c", problem = "https://atcoder.jp/contests/abc065/tasks/arc076_a" }
abc065-d = { alias = "d", problem = "https://atcoder.jp/contests/abc065/tasks/arc076_b" }

[[bin]]
name = "abc065-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc065-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc065-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc065-d"
path = "src/bin/d.rs"

[dependencies]
proconio = { version = "=0.3.6", features = ["derive"] }

[dev-dependencies]
