[package]
name = "abc392"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc392-a = { alias = "a", problem = "https://atcoder.jp/contests/abc392/tasks/abc392_a" }
abc392-b = { alias = "b", problem = "https://atcoder.jp/contests/abc392/tasks/abc392_b" }
abc392-c = { alias = "c", problem = "https://atcoder.jp/contests/abc392/tasks/abc392_c" }
abc392-d = { alias = "d", problem = "https://atcoder.jp/contests/abc392/tasks/abc392_d" }
abc392-e = { alias = "e", problem = "https://atcoder.jp/contests/abc392/tasks/abc392_e" }
abc392-f = { alias = "f", problem = "https://atcoder.jp/contests/abc392/tasks/abc392_f" }
abc392-g = { alias = "g", problem = "https://atcoder.jp/contests/abc392/tasks/abc392_g" }

[[bin]]
name = "abc392-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc392-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc392-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc392-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc392-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc392-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc392-g"
path = "src/bin/g.rs"

[dependencies]
proconio = { version = "=0.4.5", features = ["derive"] }
ac-library-rs = "=0.1.1"
superslice = "1.0.0"
itertools = "=0.11.0"
rustc-hash = "=1.1.0"

[dev-dependencies]
