[package]
name = "abc404"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc404-a = { alias = "a", problem = "https://atcoder.jp/contests/abc404/tasks/abc404_a" }
abc404-b = { alias = "b", problem = "https://atcoder.jp/contests/abc404/tasks/abc404_b" }
abc404-c = { alias = "c", problem = "https://atcoder.jp/contests/abc404/tasks/abc404_c" }
abc404-d = { alias = "d", problem = "https://atcoder.jp/contests/abc404/tasks/abc404_d" }
abc404-e = { alias = "e", problem = "https://atcoder.jp/contests/abc404/tasks/abc404_e" }
abc404-f = { alias = "f", problem = "https://atcoder.jp/contests/abc404/tasks/abc404_f" }
abc404-g = { alias = "g", problem = "https://atcoder.jp/contests/abc404/tasks/abc404_g" }

[[bin]]
name = "abc404-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc404-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc404-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc404-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc404-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc404-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc404-g"
path = "src/bin/g.rs"

[dependencies]
proconio = { version = "=0.4.5", features = ["derive"] }
ac-library-rs = "=0.1.1"
superslice = "1.0.0"
itertools = "=0.11.0"
rustc-hash = "=1.1.0"
rand = "=0.8.5"

[dev-dependencies]
