[package]
name = "abc314"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc314-a = { alias = "a", problem = "https://atcoder.jp/contests/abc314/tasks/abc314_a" }
abc314-b = { alias = "b", problem = "https://atcoder.jp/contests/abc314/tasks/abc314_b" }
abc314-c = { alias = "c", problem = "https://atcoder.jp/contests/abc314/tasks/abc314_c" }
abc314-d = { alias = "d", problem = "https://atcoder.jp/contests/abc314/tasks/abc314_d" }
abc314-e = { alias = "e", problem = "https://atcoder.jp/contests/abc314/tasks/abc314_e" }
abc314-ex = { alias = "ex", problem = "https://atcoder.jp/contests/abc314/tasks/abc314_h" }
abc314-f = { alias = "f", problem = "https://atcoder.jp/contests/abc314/tasks/abc314_f" }
abc314-g = { alias = "g", problem = "https://atcoder.jp/contests/abc314/tasks/abc314_g" }

[[bin]]
name = "abc314-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc314-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc314-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc314-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc314-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc314-ex"
path = "src/bin/ex.rs"

[[bin]]
name = "abc314-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc314-g"
path = "src/bin/g.rs"

[dependencies]
proconio = { version = "=0.3.6", features = ["derive"] }

[dev-dependencies]
