[package]
name = "abc406"
version = "0.1.0"
edition = "2021"

[package.metadata.cargo-compete.bin]
abc406-a = { alias = "a", problem = "https://atcoder.jp/contests/abc406/tasks/abc406_a" }
abc406-b = { alias = "b", problem = "https://atcoder.jp/contests/abc406/tasks/abc406_b" }
abc406-c = { alias = "c", problem = "https://atcoder.jp/contests/abc406/tasks/abc406_c" }
abc406-d = { alias = "d", problem = "https://atcoder.jp/contests/abc406/tasks/abc406_d" }
abc406-e = { alias = "e", problem = "https://atcoder.jp/contests/abc406/tasks/abc406_e" }
abc406-f = { alias = "f", problem = "https://atcoder.jp/contests/abc406/tasks/abc406_f" }
abc406-g = { alias = "g", problem = "https://atcoder.jp/contests/abc406/tasks/abc406_g" }

[[bin]]
name = "abc406-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc406-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc406-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc406-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc406-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc406-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc406-g"
path = "src/bin/g.rs"

[dependencies]
proconio = { version = "=0.4.5", features = ["derive"] }
ac-library-rs = "=0.1.1"
superslice = "1.0.0"
itertools = "=0.11.0"
num = "=0.4.1"
num-bigint = "=0.4.3"
num-complex = "=0.4.3"
num-integer = "=0.1.45"
num-iter = "=0.1.43"
num-rational = "=0.4.1"
num-traits = "=0.2.15"
num-derive = "=0.4.0"
rustc-hash = "=1.1.0"
rand = "=0.8.5"

[dev-dependencies]
