[package]
name = "abc220"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc220-a = { alias = "a", problem = "https://atcoder.jp/contests/abc220/tasks/abc220_a" }
abc220-b = { alias = "b", problem = "https://atcoder.jp/contests/abc220/tasks/abc220_b" }
abc220-c = { alias = "c", problem = "https://atcoder.jp/contests/abc220/tasks/abc220_c" }
abc220-d = { alias = "d", problem = "https://atcoder.jp/contests/abc220/tasks/abc220_d" }
abc220-e = { alias = "e", problem = "https://atcoder.jp/contests/abc220/tasks/abc220_e" }
abc220-f = { alias = "f", problem = "https://atcoder.jp/contests/abc220/tasks/abc220_f" }
abc220-g = { alias = "g", problem = "https://atcoder.jp/contests/abc220/tasks/abc220_g" }
abc220-h = { alias = "h", problem = "https://atcoder.jp/contests/abc220/tasks/abc220_h" }

[[bin]]
name = "abc220-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc220-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc220-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc220-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc220-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc220-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc220-g"
path = "src/bin/g.rs"

[[bin]]
name = "abc220-h"
path = "src/bin/h.rs"

[dependencies]
proconio = { version = "=0.3.6", features = ["derive"] }

[dev-dependencies]
