[package]
name = "abc384"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc384-a = { alias = "a", problem = "https://atcoder.jp/contests/abc384/tasks/abc384_a" }
abc384-b = { alias = "b", problem = "https://atcoder.jp/contests/abc384/tasks/abc384_b" }
abc384-c = { alias = "c", problem = "https://atcoder.jp/contests/abc384/tasks/abc384_c" }
abc384-d = { alias = "d", problem = "https://atcoder.jp/contests/abc384/tasks/abc384_d" }
abc384-e = { alias = "e", problem = "https://atcoder.jp/contests/abc384/tasks/abc384_e" }
abc384-f = { alias = "f", problem = "https://atcoder.jp/contests/abc384/tasks/abc384_f" }
abc384-g = { alias = "g", problem = "https://atcoder.jp/contests/abc384/tasks/abc384_g" }

[[bin]]
name = "abc384-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc384-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc384-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc384-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc384-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc384-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc384-g"
path = "src/bin/g.rs"

[dependencies]
proconio = { version = "=0.4.5", features = ["derive"] }
ac-library-rs = "=0.1.1"
superslice = "1.0.0"
itertools = "=0.11.0"
rustc-hash = "=1.1.0"

[dev-dependencies]
