[package]
name = "abc345"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc345-a = { alias = "a", problem = "https://atcoder.jp/contests/abc345/tasks/abc345_a" }
abc345-b = { alias = "b", problem = "https://atcoder.jp/contests/abc345/tasks/abc345_b" }
abc345-c = { alias = "c", problem = "https://atcoder.jp/contests/abc345/tasks/abc345_c" }
abc345-d = { alias = "d", problem = "https://atcoder.jp/contests/abc345/tasks/abc345_d" }
abc345-e = { alias = "e", problem = "https://atcoder.jp/contests/abc345/tasks/abc345_e" }
abc345-f = { alias = "f", problem = "https://atcoder.jp/contests/abc345/tasks/abc345_f" }
abc345-g = { alias = "g", problem = "https://atcoder.jp/contests/abc345/tasks/abc345_g" }

[[bin]]
name = "abc345-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc345-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc345-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc345-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc345-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc345-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc345-g"
path = "src/bin/g.rs"

[dependencies]
proconio = { version = "=0.3.6", features = ["derive"] }

[dev-dependencies]
