[package]
name = "abc239"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc239-a = { alias = "a", problem = "https://atcoder.jp/contests/abc239/tasks/abc239_a" }
abc239-b = { alias = "b", problem = "https://atcoder.jp/contests/abc239/tasks/abc239_b" }
abc239-c = { alias = "c", problem = "https://atcoder.jp/contests/abc239/tasks/abc239_c" }
abc239-d = { alias = "d", problem = "https://atcoder.jp/contests/abc239/tasks/abc239_d" }
abc239-e = { alias = "e", problem = "https://atcoder.jp/contests/abc239/tasks/abc239_e" }
abc239-ex = { alias = "ex", problem = "https://atcoder.jp/contests/abc239/tasks/abc239_h" }
abc239-f = { alias = "f", problem = "https://atcoder.jp/contests/abc239/tasks/abc239_f" }
abc239-g = { alias = "g", problem = "https://atcoder.jp/contests/abc239/tasks/abc239_g" }

[[bin]]
name = "abc239-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc239-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc239-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc239-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc239-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc239-ex"
path = "src/bin/ex.rs"

[[bin]]
name = "abc239-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc239-g"
path = "src/bin/g.rs"

[dependencies]
proconio = { version = "=0.3.6", features = ["derive"] }

[dev-dependencies]
