[package]
name = "abc324"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc324-a = { alias = "a", problem = "https://atcoder.jp/contests/abc324/tasks/abc324_a" }
abc324-b = { alias = "b", problem = "https://atcoder.jp/contests/abc324/tasks/abc324_b" }
abc324-c = { alias = "c", problem = "https://atcoder.jp/contests/abc324/tasks/abc324_c" }
abc324-d = { alias = "d", problem = "https://atcoder.jp/contests/abc324/tasks/abc324_d" }
abc324-e = { alias = "e", problem = "https://atcoder.jp/contests/abc324/tasks/abc324_e" }
abc324-f = { alias = "f", problem = "https://atcoder.jp/contests/abc324/tasks/abc324_f" }
abc324-g = { alias = "g", problem = "https://atcoder.jp/contests/abc324/tasks/abc324_g" }

[[bin]]
name = "abc324-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc324-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc324-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc324-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc324-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc324-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc324-g"
path = "src/bin/g.rs"

[dependencies]
proconio = { version = "=0.3.6", features = ["derive"] }

[dev-dependencies]
