[package]
name = "abc369"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc369-a = { alias = "a", problem = "https://atcoder.jp/contests/abc369/tasks/abc369_a" }
abc369-b = { alias = "b", problem = "https://atcoder.jp/contests/abc369/tasks/abc369_b" }
abc369-c = { alias = "c", problem = "https://atcoder.jp/contests/abc369/tasks/abc369_c" }
abc369-d = { alias = "d", problem = "https://atcoder.jp/contests/abc369/tasks/abc369_d" }
abc369-e = { alias = "e", problem = "https://atcoder.jp/contests/abc369/tasks/abc369_e" }
abc369-f = { alias = "f", problem = "https://atcoder.jp/contests/abc369/tasks/abc369_f" }
abc369-g = { alias = "g", problem = "https://atcoder.jp/contests/abc369/tasks/abc369_g" }

[[bin]]
name = "abc369-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc369-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc369-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc369-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc369-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc369-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc369-g"
path = "src/bin/g.rs"

[dependencies]
proconio = { version = "=0.4.5", features = ["derive"] }
ac-library-rs = "=0.1.1"
superslice = "1.0.0"
itertools = "0.13.0"

[dev-dependencies]
