[package]
name = "abc306"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc306-a = { alias = "a", problem = "https://atcoder.jp/contests/abc306/tasks/abc306_a" }
abc306-b = { alias = "b", problem = "https://atcoder.jp/contests/abc306/tasks/abc306_b" }
abc306-c = { alias = "c", problem = "https://atcoder.jp/contests/abc306/tasks/abc306_c" }
abc306-d = { alias = "d", problem = "https://atcoder.jp/contests/abc306/tasks/abc306_d" }
abc306-e = { alias = "e", problem = "https://atcoder.jp/contests/abc306/tasks/abc306_e" }
abc306-ex = { alias = "ex", problem = "https://atcoder.jp/contests/abc306/tasks/abc306_h" }
abc306-f = { alias = "f", problem = "https://atcoder.jp/contests/abc306/tasks/abc306_f" }
abc306-g = { alias = "g", problem = "https://atcoder.jp/contests/abc306/tasks/abc306_g" }

[[bin]]
name = "abc306-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc306-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc306-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc306-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc306-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc306-ex"
path = "src/bin/ex.rs"

[[bin]]
name = "abc306-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc306-g"
path = "src/bin/g.rs"

[dependencies]
proconio = { version = "=0.3.6", features = ["derive"] }

[dev-dependencies]
