[package]
name = "abc216"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc216-a = { alias = "a", problem = "https://atcoder.jp/contests/abc216/tasks/abc216_a" }
abc216-b = { alias = "b", problem = "https://atcoder.jp/contests/abc216/tasks/abc216_b" }
abc216-c = { alias = "c", problem = "https://atcoder.jp/contests/abc216/tasks/abc216_c" }
abc216-d = { alias = "d", problem = "https://atcoder.jp/contests/abc216/tasks/abc216_d" }
abc216-e = { alias = "e", problem = "https://atcoder.jp/contests/abc216/tasks/abc216_e" }
abc216-f = { alias = "f", problem = "https://atcoder.jp/contests/abc216/tasks/abc216_f" }
abc216-g = { alias = "g", problem = "https://atcoder.jp/contests/abc216/tasks/abc216_g" }
abc216-h = { alias = "h", problem = "https://atcoder.jp/contests/abc216/tasks/abc216_h" }

[[bin]]
name = "abc216-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc216-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc216-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc216-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc216-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc216-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc216-g"
path = "src/bin/g.rs"

[[bin]]
name = "abc216-h"
path = "src/bin/h.rs"

[dependencies]
proconio = { version = "=0.3.6", features = ["derive"] }

[dev-dependencies]
