[package]
name = "abc188"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc188-a = { alias = "a", problem = "https://atcoder.jp/contests/abc188/tasks/abc188_a" }
abc188-b = { alias = "b", problem = "https://atcoder.jp/contests/abc188/tasks/abc188_b" }
abc188-c = { alias = "c", problem = "https://atcoder.jp/contests/abc188/tasks/abc188_c" }
abc188-d = { alias = "d", problem = "https://atcoder.jp/contests/abc188/tasks/abc188_d" }
abc188-e = { alias = "e", problem = "https://atcoder.jp/contests/abc188/tasks/abc188_e" }
abc188-f = { alias = "f", problem = "https://atcoder.jp/contests/abc188/tasks/abc188_f" }

[[bin]]
name = "abc188-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc188-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc188-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc188-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc188-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc188-f"
path = "src/bin/f.rs"

[dependencies]
proconio = { version = "=0.3.6", features = ["derive"] }

[dev-dependencies]
