[package]
name = "abc350"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc350-a = { alias = "a", problem = "https://atcoder.jp/contests/abc350/tasks/abc350_a" }
abc350-b = { alias = "b", problem = "https://atcoder.jp/contests/abc350/tasks/abc350_b" }
abc350-c = { alias = "c", problem = "https://atcoder.jp/contests/abc350/tasks/abc350_c" }
abc350-d = { alias = "d", problem = "https://atcoder.jp/contests/abc350/tasks/abc350_d" }
abc350-e = { alias = "e", problem = "https://atcoder.jp/contests/abc350/tasks/abc350_e" }
abc350-f = { alias = "f", problem = "https://atcoder.jp/contests/abc350/tasks/abc350_f" }
abc350-g = { alias = "g", problem = "https://atcoder.jp/contests/abc350/tasks/abc350_g" }

[[bin]]
name = "abc350-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc350-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc350-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc350-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc350-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc350-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc350-g"
path = "src/bin/g.rs"

[dependencies]
proconio = { version = "=0.4.5", features = ["derive"] }
ac-library-rs = "=0.1.1"
superslice = "1.0.0"

[dev-dependencies]
