[package]
name = "abc349"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc349-a = { alias = "a", problem = "https://atcoder.jp/contests/abc349/tasks/abc349_a" }
abc349-b = { alias = "b", problem = "https://atcoder.jp/contests/abc349/tasks/abc349_b" }
abc349-c = { alias = "c", problem = "https://atcoder.jp/contests/abc349/tasks/abc349_c" }
abc349-d = { alias = "d", problem = "https://atcoder.jp/contests/abc349/tasks/abc349_d" }
abc349-e = { alias = "e", problem = "https://atcoder.jp/contests/abc349/tasks/abc349_e" }
abc349-f = { alias = "f", problem = "https://atcoder.jp/contests/abc349/tasks/abc349_f" }
abc349-g = { alias = "g", problem = "https://atcoder.jp/contests/abc349/tasks/abc349_g" }

[[bin]]
name = "abc349-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc349-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc349-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc349-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc349-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc349-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc349-g"
path = "src/bin/g.rs"

[dependencies]
proconio = { version = "=0.3.6", features = ["derive"] }

[dev-dependencies]
