[package]
name = "abc337"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc337-a = { alias = "a", problem = "https://atcoder.jp/contests/abc337/tasks/abc337_a" }
abc337-b = { alias = "b", problem = "https://atcoder.jp/contests/abc337/tasks/abc337_b" }
abc337-c = { alias = "c", problem = "https://atcoder.jp/contests/abc337/tasks/abc337_c" }
abc337-d = { alias = "d", problem = "https://atcoder.jp/contests/abc337/tasks/abc337_d" }
abc337-e = { alias = "e", problem = "https://atcoder.jp/contests/abc337/tasks/abc337_e" }
abc337-f = { alias = "f", problem = "https://atcoder.jp/contests/abc337/tasks/abc337_f" }
abc337-g = { alias = "g", problem = "https://atcoder.jp/contests/abc337/tasks/abc337_g" }

[[bin]]
name = "abc337-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc337-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc337-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc337-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc337-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc337-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc337-g"
path = "src/bin/g.rs"

[dependencies]
proconio = { version = "=0.3.6", features = ["derive"] }

[dev-dependencies]
