[package]
name = "abc321"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc321-a = { alias = "a", problem = "https://atcoder.jp/contests/abc321/tasks/abc321_a" }
abc321-b = { alias = "b", problem = "https://atcoder.jp/contests/abc321/tasks/abc321_b" }
abc321-c = { alias = "c", problem = "https://atcoder.jp/contests/abc321/tasks/abc321_c" }
abc321-d = { alias = "d", problem = "https://atcoder.jp/contests/abc321/tasks/abc321_d" }
abc321-e = { alias = "e", problem = "https://atcoder.jp/contests/abc321/tasks/abc321_e" }
abc321-f = { alias = "f", problem = "https://atcoder.jp/contests/abc321/tasks/abc321_f" }
abc321-g = { alias = "g", problem = "https://atcoder.jp/contests/abc321/tasks/abc321_g" }

[[bin]]
name = "abc321-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc321-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc321-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc321-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc321-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc321-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc321-g"
path = "src/bin/g.rs"

[dependencies]
itertools = "0.12.0"
proconio = { version = "=0.3.6", features = ["derive"] }

[dev-dependencies]
