[package]
name = "abc366"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc366-a = { alias = "a", problem = "https://atcoder.jp/contests/abc366/tasks/abc366_a" }
abc366-b = { alias = "b", problem = "https://atcoder.jp/contests/abc366/tasks/abc366_b" }
abc366-c = { alias = "c", problem = "https://atcoder.jp/contests/abc366/tasks/abc366_c" }
abc366-d = { alias = "d", problem = "https://atcoder.jp/contests/abc366/tasks/abc366_d" }
abc366-e = { alias = "e", problem = "https://atcoder.jp/contests/abc366/tasks/abc366_e" }
abc366-f = { alias = "f", problem = "https://atcoder.jp/contests/abc366/tasks/abc366_f" }
abc366-g = { alias = "g", problem = "https://atcoder.jp/contests/abc366/tasks/abc366_g" }

[[bin]]
name = "abc366-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc366-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc366-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc366-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc366-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc366-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc366-g"
path = "src/bin/g.rs"

[dependencies]
proconio = { version = "=0.4.5", features = ["derive"] }
ac-library-rs = "=0.1.1"
superslice = "1.0.0"

[dev-dependencies]
