[package]
name = "abc197"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc197-a = { alias = "a", problem = "https://atcoder.jp/contests/abc197/tasks/abc197_a" }
abc197-b = { alias = "b", problem = "https://atcoder.jp/contests/abc197/tasks/abc197_b" }
abc197-c = { alias = "c", problem = "https://atcoder.jp/contests/abc197/tasks/abc197_c" }
abc197-d = { alias = "d", problem = "https://atcoder.jp/contests/abc197/tasks/abc197_d" }
abc197-e = { alias = "e", problem = "https://atcoder.jp/contests/abc197/tasks/abc197_e" }
abc197-f = { alias = "f", problem = "https://atcoder.jp/contests/abc197/tasks/abc197_f" }

[[bin]]
name = "abc197-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc197-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc197-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc197-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc197-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc197-f"
path = "src/bin/f.rs"

[dependencies]
proconio = { version = "=0.3.6", features = ["derive"] }

[dev-dependencies]
