[package]
name = "abc224"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc224-a = { alias = "a", problem = "https://atcoder.jp/contests/abc224/tasks/abc224_a" }
abc224-b = { alias = "b", problem = "https://atcoder.jp/contests/abc224/tasks/abc224_b" }
abc224-c = { alias = "c", problem = "https://atcoder.jp/contests/abc224/tasks/abc224_c" }
abc224-d = { alias = "d", problem = "https://atcoder.jp/contests/abc224/tasks/abc224_d" }
abc224-e = { alias = "e", problem = "https://atcoder.jp/contests/abc224/tasks/abc224_e" }
abc224-f = { alias = "f", problem = "https://atcoder.jp/contests/abc224/tasks/abc224_f" }
abc224-g = { alias = "g", problem = "https://atcoder.jp/contests/abc224/tasks/abc224_g" }
abc224-h = { alias = "h", problem = "https://atcoder.jp/contests/abc224/tasks/abc224_h" }

[[bin]]
name = "abc224-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc224-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc224-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc224-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc224-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc224-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc224-g"
path = "src/bin/g.rs"

[[bin]]
name = "abc224-h"
path = "src/bin/h.rs"

[dependencies]
proconio = { version = "=0.3.6", features = ["derive"] }

[dev-dependencies]
