[package]
name = "abc301"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc301-a = { alias = "a", problem = "https://atcoder.jp/contests/abc301/tasks/abc301_a" }
abc301-b = { alias = "b", problem = "https://atcoder.jp/contests/abc301/tasks/abc301_b" }
abc301-c = { alias = "c", problem = "https://atcoder.jp/contests/abc301/tasks/abc301_c" }
abc301-d = { alias = "d", problem = "https://atcoder.jp/contests/abc301/tasks/abc301_d" }
abc301-e = { alias = "e", problem = "https://atcoder.jp/contests/abc301/tasks/abc301_e" }
abc301-ex = { alias = "ex", problem = "https://atcoder.jp/contests/abc301/tasks/abc301_h" }
abc301-f = { alias = "f", problem = "https://atcoder.jp/contests/abc301/tasks/abc301_f" }
abc301-g = { alias = "g", problem = "https://atcoder.jp/contests/abc301/tasks/abc301_g" }

[[bin]]
name = "abc301-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc301-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc301-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc301-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc301-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc301-ex"
path = "src/bin/ex.rs"

[[bin]]
name = "abc301-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc301-g"
path = "src/bin/g.rs"

[dependencies]
proconio = { version = "=0.3.6", features = ["derive"] }

[dev-dependencies]
