[package]
name = "abc319"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc319-a = { alias = "a", problem = "https://atcoder.jp/contests/abc319/tasks/abc319_a" }
abc319-b = { alias = "b", problem = "https://atcoder.jp/contests/abc319/tasks/abc319_b" }
abc319-c = { alias = "c", problem = "https://atcoder.jp/contests/abc319/tasks/abc319_c" }
abc319-d = { alias = "d", problem = "https://atcoder.jp/contests/abc319/tasks/abc319_d" }
abc319-e = { alias = "e", problem = "https://atcoder.jp/contests/abc319/tasks/abc319_e" }
abc319-f = { alias = "f", problem = "https://atcoder.jp/contests/abc319/tasks/abc319_f" }
abc319-g = { alias = "g", problem = "https://atcoder.jp/contests/abc319/tasks/abc319_g" }

[[bin]]
name = "abc319-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc319-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc319-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc319-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc319-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc319-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc319-g"
path = "src/bin/g.rs"

[dependencies]
itertools = "0.13.0"
proconio = { version = "=0.3.6", features = ["derive"] }

[dev-dependencies]
