[package]
name = "abc238"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc238-a = { alias = "a", problem = "https://atcoder.jp/contests/abc238/tasks/abc238_a" }
abc238-b = { alias = "b", problem = "https://atcoder.jp/contests/abc238/tasks/abc238_b" }
abc238-c = { alias = "c", problem = "https://atcoder.jp/contests/abc238/tasks/abc238_c" }
abc238-d = { alias = "d", problem = "https://atcoder.jp/contests/abc238/tasks/abc238_d" }
abc238-e = { alias = "e", problem = "https://atcoder.jp/contests/abc238/tasks/abc238_e" }
abc238-ex = { alias = "ex", problem = "https://atcoder.jp/contests/abc238/tasks/abc238_h" }
abc238-f = { alias = "f", problem = "https://atcoder.jp/contests/abc238/tasks/abc238_f" }
abc238-g = { alias = "g", problem = "https://atcoder.jp/contests/abc238/tasks/abc238_g" }

[[bin]]
name = "abc238-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc238-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc238-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc238-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc238-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc238-ex"
path = "src/bin/ex.rs"

[[bin]]
name = "abc238-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc238-g"
path = "src/bin/g.rs"

[dependencies]
proconio = { version = "=0.3.6", features = ["derive"] }

[dev-dependencies]
