[package]
name = "abc383"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc383-a = { alias = "a", problem = "https://atcoder.jp/contests/abc383/tasks/abc383_a" }
abc383-b = { alias = "b", problem = "https://atcoder.jp/contests/abc383/tasks/abc383_b" }
abc383-c = { alias = "c", problem = "https://atcoder.jp/contests/abc383/tasks/abc383_c" }
abc383-d = { alias = "d", problem = "https://atcoder.jp/contests/abc383/tasks/abc383_d" }
abc383-e = { alias = "e", problem = "https://atcoder.jp/contests/abc383/tasks/abc383_e" }
abc383-f = { alias = "f", problem = "https://atcoder.jp/contests/abc383/tasks/abc383_f" }
abc383-g = { alias = "g", problem = "https://atcoder.jp/contests/abc383/tasks/abc383_g" }

[[bin]]
name = "abc383-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc383-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc383-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc383-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc383-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc383-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc383-g"
path = "src/bin/g.rs"

[dependencies]
proconio = { version = "=0.4.5", features = ["derive"] }
ac-library-rs = "=0.1.1"
superslice = "1.0.0"
itertools = "0.13.0"

[dev-dependencies]
