[package]
name = "abc343"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc343-a = { alias = "a", problem = "https://atcoder.jp/contests/abc343/tasks/abc343_a" }
abc343-b = { alias = "b", problem = "https://atcoder.jp/contests/abc343/tasks/abc343_b" }
abc343-c = { alias = "c", problem = "https://atcoder.jp/contests/abc343/tasks/abc343_c" }
abc343-d = { alias = "d", problem = "https://atcoder.jp/contests/abc343/tasks/abc343_d" }
abc343-e = { alias = "e", problem = "https://atcoder.jp/contests/abc343/tasks/abc343_e" }
abc343-f = { alias = "f", problem = "https://atcoder.jp/contests/abc343/tasks/abc343_f" }
abc343-g = { alias = "g", problem = "https://atcoder.jp/contests/abc343/tasks/abc343_g" }

[[bin]]
name = "abc343-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc343-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc343-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc343-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc343-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc343-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc343-g"
path = "src/bin/g.rs"

[dependencies]
proconio = { version = "=0.3.6", features = ["derive"] }

[dev-dependencies]
