[package]
name = "abc309"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc309-a = { alias = "a", problem = "https://atcoder.jp/contests/abc309/tasks/abc309_a" }
abc309-b = { alias = "b", problem = "https://atcoder.jp/contests/abc309/tasks/abc309_b" }
abc309-c = { alias = "c", problem = "https://atcoder.jp/contests/abc309/tasks/abc309_c" }
abc309-d = { alias = "d", problem = "https://atcoder.jp/contests/abc309/tasks/abc309_d" }
abc309-e = { alias = "e", problem = "https://atcoder.jp/contests/abc309/tasks/abc309_e" }
abc309-ex = { alias = "ex", problem = "https://atcoder.jp/contests/abc309/tasks/abc309_h" }
abc309-f = { alias = "f", problem = "https://atcoder.jp/contests/abc309/tasks/abc309_f" }
abc309-g = { alias = "g", problem = "https://atcoder.jp/contests/abc309/tasks/abc309_g" }

[[bin]]
name = "abc309-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc309-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc309-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc309-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc309-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc309-ex"
path = "src/bin/ex.rs"

[[bin]]
name = "abc309-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc309-g"
path = "src/bin/g.rs"

[dependencies]
proconio = { version = "=0.3.6", features = ["derive"] }

[dev-dependencies]
