[package]
name = "abc338"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc338-a = { alias = "a", problem = "https://atcoder.jp/contests/abc338/tasks/abc338_a" }
abc338-b = { alias = "b", problem = "https://atcoder.jp/contests/abc338/tasks/abc338_b" }
abc338-c = { alias = "c", problem = "https://atcoder.jp/contests/abc338/tasks/abc338_c" }
abc338-d = { alias = "d", problem = "https://atcoder.jp/contests/abc338/tasks/abc338_d" }
abc338-e = { alias = "e", problem = "https://atcoder.jp/contests/abc338/tasks/abc338_e" }
abc338-f = { alias = "f", problem = "https://atcoder.jp/contests/abc338/tasks/abc338_f" }
abc338-g = { alias = "g", problem = "https://atcoder.jp/contests/abc338/tasks/abc338_g" }

[[bin]]
name = "abc338-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc338-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc338-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc338-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc338-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc338-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc338-g"
path = "src/bin/g.rs"

[dependencies]
proconio = { version = "=0.3.6", features = ["derive"] }

[dev-dependencies]
