[package]
name = "abc362"
version = "0.1.0"
edition = "2021"

[package.metadata.cargo-compete.bin]
abc362-a = { alias = "a", problem = "https://atcoder.jp/contests/abc362/tasks/abc362_a" }
abc362-b = { alias = "b", problem = "https://atcoder.jp/contests/abc362/tasks/abc362_b" }
abc362-c = { alias = "c", problem = "https://atcoder.jp/contests/abc362/tasks/abc362_c" }
abc362-d = { alias = "d", problem = "https://atcoder.jp/contests/abc362/tasks/abc362_d" }
abc362-e = { alias = "e", problem = "https://atcoder.jp/contests/abc362/tasks/abc362_e" }
abc362-f = { alias = "f", problem = "https://atcoder.jp/contests/abc362/tasks/abc362_f" }
abc362-g = { alias = "g", problem = "https://atcoder.jp/contests/abc362/tasks/abc362_g" }

[[bin]]
name = "abc362-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc362-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc362-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc362-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc362-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc362-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc362-g"
path = "src/bin/g.rs"

[dependencies]
proconio = { version = "=0.4.5", features = ["derive"] }
ac-library-rs = "=0.1.1"
superslice = "1.0.0"
itertools = "=0.11.0"
num = "=0.4.1"
num-bigint = "=0.4.3"
num-complex = "=0.4.3"
num-integer = "=0.1.45"
num-iter = "=0.1.43"
num-rational = "=0.4.1"
num-traits = "=0.2.15"
num-derive = "=0.4.0"
rustc-hash = "=1.1.0"
rand = "=0.8.5"

[dev-dependencies]
