[package]
name = "abc344"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc344-a = { alias = "a", problem = "https://atcoder.jp/contests/abc344/tasks/abc344_a" }
abc344-b = { alias = "b", problem = "https://atcoder.jp/contests/abc344/tasks/abc344_b" }
abc344-c = { alias = "c", problem = "https://atcoder.jp/contests/abc344/tasks/abc344_c" }
abc344-d = { alias = "d", problem = "https://atcoder.jp/contests/abc344/tasks/abc344_d" }
abc344-e = { alias = "e", problem = "https://atcoder.jp/contests/abc344/tasks/abc344_e" }
abc344-f = { alias = "f", problem = "https://atcoder.jp/contests/abc344/tasks/abc344_f" }
abc344-g = { alias = "g", problem = "https://atcoder.jp/contests/abc344/tasks/abc344_g" }

[[bin]]
name = "abc344-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc344-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc344-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc344-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc344-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc344-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc344-g"
path = "src/bin/g.rs"

[dependencies]
proconio = { version = "=0.3.6", features = ["derive"] }

[dev-dependencies]
