[package]
name = "abc377"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc377-a = { alias = "a", problem = "https://atcoder.jp/contests/abc377/tasks/abc377_a" }
abc377-b = { alias = "b", problem = "https://atcoder.jp/contests/abc377/tasks/abc377_b" }
abc377-c = { alias = "c", problem = "https://atcoder.jp/contests/abc377/tasks/abc377_c" }
abc377-d = { alias = "d", problem = "https://atcoder.jp/contests/abc377/tasks/abc377_d" }
abc377-e = { alias = "e", problem = "https://atcoder.jp/contests/abc377/tasks/abc377_e" }
abc377-f = { alias = "f", problem = "https://atcoder.jp/contests/abc377/tasks/abc377_f" }
abc377-g = { alias = "g", problem = "https://atcoder.jp/contests/abc377/tasks/abc377_g" }

[[bin]]
name = "abc377-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc377-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc377-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc377-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc377-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc377-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc377-g"
path = "src/bin/g.rs"

[dependencies]
proconio = { version = "=0.4.5", features = ["derive"] }
ac-library-rs = "=0.1.1"
superslice = "1.0.0"
itertools = "0.13.0"

[dev-dependencies]
