[package]
name = "abc336"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc336-a = { alias = "a", problem = "https://atcoder.jp/contests/abc336/tasks/abc336_a" }
abc336-b = { alias = "b", problem = "https://atcoder.jp/contests/abc336/tasks/abc336_b" }
abc336-c = { alias = "c", problem = "https://atcoder.jp/contests/abc336/tasks/abc336_c" }
abc336-d = { alias = "d", problem = "https://atcoder.jp/contests/abc336/tasks/abc336_d" }
abc336-e = { alias = "e", problem = "https://atcoder.jp/contests/abc336/tasks/abc336_e" }
abc336-f = { alias = "f", problem = "https://atcoder.jp/contests/abc336/tasks/abc336_f" }
abc336-g = { alias = "g", problem = "https://atcoder.jp/contests/abc336/tasks/abc336_g" }

[[bin]]
name = "abc336-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc336-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc336-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc336-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc336-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc336-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc336-g"
path = "src/bin/g.rs"

[dependencies]
proconio = { version = "=0.3.6", features = ["derive"] }

[dev-dependencies]
