[package]
name = "abc396"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc396-a = { alias = "a", problem = "https://atcoder.jp/contests/abc396/tasks/abc396_a" }
abc396-b = { alias = "b", problem = "https://atcoder.jp/contests/abc396/tasks/abc396_b" }
abc396-c = { alias = "c", problem = "https://atcoder.jp/contests/abc396/tasks/abc396_c" }
abc396-d = { alias = "d", problem = "https://atcoder.jp/contests/abc396/tasks/abc396_d" }
abc396-e = { alias = "e", problem = "https://atcoder.jp/contests/abc396/tasks/abc396_e" }
abc396-f = { alias = "f", problem = "https://atcoder.jp/contests/abc396/tasks/abc396_f" }
abc396-g = { alias = "g", problem = "https://atcoder.jp/contests/abc396/tasks/abc396_g" }

[[bin]]
name = "abc396-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc396-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc396-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc396-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc396-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc396-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc396-g"
path = "src/bin/g.rs"

[dependencies]
proconio = { version = "=0.4.5", features = ["derive"] }
ac-library-rs = "=0.1.1"
superslice = "1.0.0"
itertools = "=0.11.0"
rustc-hash = "=1.1.0"

[dev-dependencies]
