[package]
name = "abc317"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc317-a = { alias = "a", problem = "https://atcoder.jp/contests/abc317/tasks/abc317_a" }
abc317-b = { alias = "b", problem = "https://atcoder.jp/contests/abc317/tasks/abc317_b" }
abc317-c = { alias = "c", problem = "https://atcoder.jp/contests/abc317/tasks/abc317_c" }
abc317-d = { alias = "d", problem = "https://atcoder.jp/contests/abc317/tasks/abc317_d" }
abc317-e = { alias = "e", problem = "https://atcoder.jp/contests/abc317/tasks/abc317_e" }
abc317-ex = { alias = "ex", problem = "https://atcoder.jp/contests/abc317/tasks/abc317_h" }
abc317-f = { alias = "f", problem = "https://atcoder.jp/contests/abc317/tasks/abc317_f" }
abc317-g = { alias = "g", problem = "https://atcoder.jp/contests/abc317/tasks/abc317_g" }

[[bin]]
name = "abc317-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc317-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc317-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc317-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc317-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc317-ex"
path = "src/bin/ex.rs"

[[bin]]
name = "abc317-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc317-g"
path = "src/bin/g.rs"

[dependencies]
proconio = { version = "=0.3.6", features = ["derive"] }

[dev-dependencies]
