[package]
name = "abc399"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc399-a = { alias = "a", problem = "https://atcoder.jp/contests/abc399/tasks/abc399_a" }
abc399-b = { alias = "b", problem = "https://atcoder.jp/contests/abc399/tasks/abc399_b" }
abc399-c = { alias = "c", problem = "https://atcoder.jp/contests/abc399/tasks/abc399_c" }
abc399-d = { alias = "d", problem = "https://atcoder.jp/contests/abc399/tasks/abc399_d" }
abc399-e = { alias = "e", problem = "https://atcoder.jp/contests/abc399/tasks/abc399_e" }
abc399-f = { alias = "f", problem = "https://atcoder.jp/contests/abc399/tasks/abc399_f" }
abc399-g = { alias = "g", problem = "https://atcoder.jp/contests/abc399/tasks/abc399_g" }

[[bin]]
name = "abc399-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc399-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc399-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc399-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc399-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc399-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc399-g"
path = "src/bin/g.rs"

[dependencies]
proconio = { version = "=0.4.5", features = ["derive"] }
ac-library-rs = "=0.1.1"
superslice = "1.0.0"
itertools = "=0.11.0"
rustc-hash = "=1.1.0"
rand = "=0.8.5"

[dev-dependencies]
