[package]
name = "abc351"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc351-a = { alias = "a", problem = "https://atcoder.jp/contests/abc351/tasks/abc351_a" }
abc351-b = { alias = "b", problem = "https://atcoder.jp/contests/abc351/tasks/abc351_b" }
abc351-c = { alias = "c", problem = "https://atcoder.jp/contests/abc351/tasks/abc351_c" }
abc351-d = { alias = "d", problem = "https://atcoder.jp/contests/abc351/tasks/abc351_d" }
abc351-e = { alias = "e", problem = "https://atcoder.jp/contests/abc351/tasks/abc351_e" }
abc351-f = { alias = "f", problem = "https://atcoder.jp/contests/abc351/tasks/abc351_f" }
abc351-g = { alias = "g", problem = "https://atcoder.jp/contests/abc351/tasks/abc351_g" }

[[bin]]
name = "abc351-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc351-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc351-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc351-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc351-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc351-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc351-g"
path = "src/bin/g.rs"

[dependencies]
proconio = { version = "=0.4.5", features = ["derive"] }
ac-library-rs = "=0.1.1"
superslice = "1.0.0"

[dev-dependencies]
